//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UtilizaServico.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClienteEntidade", Namespace="http://schemas.datacontract.org/2004/07/Clientes")]
    [System.SerializableAttribute()]
    public partial class ClienteEntidade : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CPFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CPF {
            get {
                return this.CPFField;
            }
            set {
                if ((object.ReferenceEquals(this.CPFField, value) != true)) {
                    this.CPFField = value;
                    this.RaisePropertyChanged("CPF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IClienteService")]
    public interface IClienteService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/GetCliente", ReplyAction="http://tempuri.org/IClienteService/GetClienteResponse")]
        UtilizaServico.ServiceReference1.ClienteEntidade GetCliente(string nome);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/GetCliente", ReplyAction="http://tempuri.org/IClienteService/GetClienteResponse")]
        System.Threading.Tasks.Task<UtilizaServico.ServiceReference1.ClienteEntidade> GetClienteAsync(string nome);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/AddCliente", ReplyAction="http://tempuri.org/IClienteService/AddClienteResponse")]
        void AddCliente(UtilizaServico.ServiceReference1.ClienteEntidade clienteEntidade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/AddCliente", ReplyAction="http://tempuri.org/IClienteService/AddClienteResponse")]
        System.Threading.Tasks.Task AddClienteAsync(UtilizaServico.ServiceReference1.ClienteEntidade clienteEntidade);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IClienteServiceChannel : UtilizaServico.ServiceReference1.IClienteService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClienteServiceClient : System.ServiceModel.ClientBase<UtilizaServico.ServiceReference1.IClienteService>, UtilizaServico.ServiceReference1.IClienteService {
        
        public ClienteServiceClient() {
        }
        
        public ClienteServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClienteServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClienteServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClienteServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public UtilizaServico.ServiceReference1.ClienteEntidade GetCliente(string nome) {
            return base.Channel.GetCliente(nome);
        }
        
        public System.Threading.Tasks.Task<UtilizaServico.ServiceReference1.ClienteEntidade> GetClienteAsync(string nome) {
            return base.Channel.GetClienteAsync(nome);
        }
        
        public void AddCliente(UtilizaServico.ServiceReference1.ClienteEntidade clienteEntidade) {
            base.Channel.AddCliente(clienteEntidade);
        }
        
        public System.Threading.Tasks.Task AddClienteAsync(UtilizaServico.ServiceReference1.ClienteEntidade clienteEntidade) {
            return base.Channel.AddClienteAsync(clienteEntidade);
        }
    }
}
